### ISSUE TITLE
tensorflow.python.framework.errors_impl.InvalidArgumentError

### ISSUE THREAD

**Issue by tjulearning** [bubbliiiing/mask-rcnn-tf2#3]
博主您好，shape数据集未更改其他参数，在运行train文件的epoch1时有如下报错，请问是图像尺寸的问题吗？如果是应该如何修改？感谢您的回复！
tensorflow.python.framework.errors_impl.InvalidArgumentError: indices[1] = 127306 is not in [0, 65472)
	 [[{{node ROI/GatherV2_4}}]]

**Comment by tjulearning** [comment]
> 博主您好，shape数据集未更改其他参数，在运行train文件的epoch1时有如下报错，请问是图像尺寸的问题吗？如果是应该如何修改？感谢您的回复！ tensorflow.python.framework.errors_impl.InvalidArgumentError: indices[1] = 127306 is not in [0, 65472) [[{{node ROI/GatherV2_4}}]]

自定义数据集也是同样的问题，应该是尺寸计算出错，但是具体细节不清楚是在哪里，希望博主能够指点一下！非常感谢！

**Comment by tjulearning** [comment]
> 怎么感觉不是版本就是显存不足呢
我查看了电脑显示内存是8G+，运行至最后callback报错，
Traceback (most recent call last):
  File "E:/CODE/maskrcnn/mask-rcnn-tf2-master/train.py", line 296, in <module>
    callbacks           = callbacks

**Comment by tjulearning** [comment]
> 怎么感觉不是版本就是显存不足呢

我查看了电脑显示内存是8G+，运行至最后callback报错，
Traceback (most recent call last):
  File "E:/CODE/maskrcnn/mask-rcnn-tf2-master/train.py", line 296, in <module>
    callbacks           = callbacks

**Comment by bubbliiiing** [comment]
你仔细看我说的话…我并没有说内存…

**Comment by tjulearning** [comment]
> 你仔细看我说的话…我并没有说内存…

不好意思。。显存不是显示内存么，应该是够的。版本原因还是不太明白怎么解决

**Comment by tjulearning** [comment]
> 你不要应该…，你去了解一下你自己的显存和版本到底是啥吧。

解决了，用2.6.0的tf可以运行

**Comment by daixin0609** [comment]
> 

各位前辈，我也遇到了这个问题，使用2.2或2.6版本的tf均存在问题
![image](https://user-images.githubusercontent.com/124659246/217497322-34a68e7c-b48e-465d-a0e1-3308ceb405e0.png)
