### ISSUE TITLE
AttributeError: Can't get attribute 'TrainConfig' on <module '__mp_main__' from 'D:\\my_job\\MY_Github\\mask-rcnn-keras-master\\train.py'>

### ISSUE THREAD

**Issue by songjiahao-wq** [bubbliiiing/mask-rcnn-tf2#39]
Using TensorFlow backend.
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "C:\ProgramData\anaconda3\envs\keras_3.6\lib\multiprocessing\spawn.py", line 105, in spawn_main
    exitcode = _main(fd)
  File "C:\ProgramData\anaconda3\envs\keras_3.6\lib\multiprocessing\spawn.py", line 115, in _main
    self = reduction.pickle.load(from_parent)
AttributeError: Can't get attribute 'TrainConfig' on <module '__mp_main__' from 'D:\\my_job\\MY_Github\\mask-rcnn-keras-master\\train.py'>
请问这是为什么呢，一直没解决

**Comment by bubbliiiing** [comment]
截图看看

**Comment by DennisJcy** [comment]
num_workers设置为1
